apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-app
  labels:
    app: spotify-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spotify-app
  template:
    metadata:
      labels:
        app:spotify-app
    spec:
      containers:
      - name: spotify-app-container
        image: whamouda1/spotify-app:latest  # Replace with your Docker image
        ports:
        - containerPort: 3000  # Replace with the port your app runs on
