apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-app
  labels:
    app: spotify-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spotify-app
  template:
    metadata:
      labels:
        app: spotify-app
    spec:
      containers:
      - name: spotify-app
        image: whamouda1/spotify-app:latest
        ports:
        - containerPort: 8080  # Adjust this port based on your application
        env:
        - name: ENV_VAR_NAME  # Replace with actual environment variables needed for your app
          value: "value"
