apiVersion: v1
kind: Service
metadata:
  name: spotify-app
spec:
  type: LoadBalancer  # Use LoadBalancer for external access, or ClusterIP for internal
  ports:
  - port: 80  # The port exposed by the service
    targetPort: 8080  # The port on which your app is running
  selector:
    app: spotify-app
